# Generated by Django 4.1.4 on 2023-02-05 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='date',
        ),
        migrations.AlterField(
            model_name='conversation',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
