# Generated by Django 4.1.4 on 2023-02-03 03:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_conversation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='date',
            field=models.DateField(default=datetime.date(2023, 2, 3)),
        ),
    ]
