# Generated by Django 4.1.4 on 2023-02-01 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_client_meet_conversation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='creared_date',
            field=models.DateField(default=datetime.date(2023, 2, 1)),
        ),
    ]
